export const QUIZ = {
  
  QUIZ_STEP_VALID     : 'QUIZ_STEP_VALID',
  QUIZ_STEP_INVALID   : 'QUIZ_STEP_INVALID',

  QUIZ_INTRO_STEP     : 'QUIZ_INTRO_STEP',
  QUIZ_QUESTIONS_STEP : 'QUIZ_QUESTIONS_STEP',
  QUIZ_SUM_UP_STEP    : 'QUIZ_SUM_UP_STEP',
  QUIZ_DONE           : 'QUIZ_DONE',  

  QUIZ_MOVE_START       : 'QUIZ_MOVE_START',
  QUIZ_MOVE_GO_NEXT     : 'QUIZ_MOVE_GO_NEXT',
  QUIZ_MOVE_GO_PREVIOUS : 'QUIZ_MOVE_GO_PREVIOUS',  
  QUIZ_MOVE_END         : 'QUIZ_MOVE_END'
};
